2022-09-09 11:25:18,719 - __main__ - INFO - xiaomi_jd_openCard(-1001420873978)消息：1
2022-09-09 11:25:21,722 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:25:25,622 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:25:29,536 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:25:33,452 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:25:37,366 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:25:41,296 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:25:45,202 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:25:49,289 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:25:53,239 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:25:57,176 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:01,132 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:05,036 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:08,996 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:12,936 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:16,836 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:20,729 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:24,636 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:28,559 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:32,459 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:35,121 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:36,356 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:39,102 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:40,562 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:43,012 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:44,532 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:46,959 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:48,469 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:50,922 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:52,419 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:54,892 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:56,372 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:26:58,822 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:00,299 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:02,739 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:04,222 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:06,762 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:08,159 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:10,729 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:12,099 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:14,719 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:16,072 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:19,992 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:20,102 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:23,912 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:24,019 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:27,882 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:27,932 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:32,406 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:32,416 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:35,161 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:36,362 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:36,382 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:40,346 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:43,279 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:44,309 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:48,279 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:50,252 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:52,206 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:54,173 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:56,146 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:27:58,109 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:28:05,052 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:28:22,647 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:29:39,157 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 11:29:56,873 - __main__ - INFO - xiaomi_jd_openCard(-1001420873978)消息：test
2022-09-09 11:30:11,847 - __main__ - INFO - 9
2022-09-09 11:30:11,848 - __main__ - INFO - 文件下载成功:新建 文本文档.txt
2022-09-09 11:30:13,225 - __main__ - INFO - git push
2022-09-09 11:30:29,201 - __main__ - INFO - xiaomi_jd_openCard(-1001420873978)消息：删除 新建 文本文档.txt
2022-09-09 11:30:31,737 - __main__ - INFO - git push
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/contrib/pyopenssl.py", line 488, in wrap_socket
    cnx.do_handshake()
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/SSL.py", line 1991, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.8/dist-packages/OpenSSL/SSL.py", line 1692, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 667, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 932, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/contrib/pyopenssl.py", line 494, in wrap_socket
    raise ssl.SSLError("bad handshake: %r" % e)
ssl.SSLError: ("bad handshake: SysCallError(104, 'ECONNRESET')",)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 446, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5528541550:AAHMN2eOC-6W1PkreoQcHfnIwhEzjXmecg4/getUpdates?offset=512326561 (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tgFileBot.py", line 133, in <module>
    getUpdates(updateId)
  File "tgFileBot.py", line 49, in getUpdates
    response = requests.request("GET", url, data=None, headers=None,proxies=proxies,verify=False)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.telegram.org', port=443): Max retries exceeded with url: /bot5528541550:AAHMN2eOC-6W1PkreoQcHfnIwhEzjXmecg4/getUpdates?offset=512326561 (Caused by SSLError(SSLError("bad handshake: SysCallError(104, 'ECONNRESET')")))
2022-09-09 23:52:45,109 - __main__ - INFO - 启动成功，开始监听群消息
2022-09-09 23:52:49,380 - __main__ - INFO - 9
2022-09-09 23:52:49,381 - __main__ - INFO - 文件下载成功:新建 文本文档.txt
